#!/usr/bin/env python3
"""Generate a reviewable translation template from ``values/strings.xml``.

Why this exists
---------------
Santali is not a language this project can machine-translate honestly. The fire
module tells a trainee which extinguisher is safe on a live electrical panel; a
plausible-looking wrong translation of that string is a safety defect, not a
cosmetic one. So instead of guessing, the Santali resource files are generated as
*templates*: the handful of strings we are genuinely confident about are real
translations, and every other key is emitted as a TODO comment holding the
ready-to-fill element.

Two properties fall out of that:

* Android's resource fallback means a key that is absent from ``values-sat/``
  resolves to ``values/`` at runtime. An untranslated screen shows English —
  readable by a supervisor — rather than a blank or a crash.
* Uncommenting a TODO line and replacing the English text is the whole editing
  workflow for the native speaker reviewing this. No key lists to cross-check,
  no format-specifier archaeology.

Regenerate after changing ``values/strings.xml``; existing translations in the
CONFIDENT tables below survive, new English keys arrive as fresh TODOs.

Usage::

    python3 tools/generate_translation_template.py

Writes ``values-sat/strings.xml`` (Ol Chiki) and ``values-b+sat+Deva/strings.xml``
(transliterated Devanagari).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RES = REPO / "app" / "src" / "main" / "res"
SOURCE = RES / "values" / "strings.xml"

# A single-line <string> element, which is how values/strings.xml is written.
STRING_RE = re.compile(r'^<string\s+name="(?P<name>[^"]+)"(?P<attrs>[^>]*)>.*</string>$')
FORMAT_RE = re.compile(r"%\d+\$[0-9.,+\-# (]*[a-zA-Z]")

# ---------------------------------------------------------------------------
# What we are actually confident of.
#
# Keep this list *short*. Every entry here is a claim that the translation is
# correct, and an entry added on a hunch is worse than a TODO: a reviewer skims
# past a filled-in string and stops at a TODO.
#
#   ᱡᱚᱦᱟᱨ / जोहार  "Johar", the standard Santali greeting.
#   ᱥᱟᱱᱛᱟᱲᱤ         the Santali endonym (s-a-n-t-a-ṛ-i), used on the picker row.
#
# The rest are format-only strings: no words, so nothing to mistranslate. They
# are listed rather than left to fall back because a translator opening the file
# should see that the placeholders are deliberate and must not be reordered.
# ---------------------------------------------------------------------------

FORMAT_ONLY = {
    "certificate_score": "%1$d / 100",
    "fire_module_elapsed": "%1$02d:%2$02d",
    "fire_module_results_score": "%1$d / %2$d",
}

CONFIDENT_OLCK = {
    # A product name, left as-is in every locale.
    "app_name": "MineSafeAR",
    "home_greeting": "ᱡᱚᱦᱟᱨ MineSafeAR",
    **FORMAT_ONLY,
}

CONFIDENT_DEVA = {
    "app_name": "MineSafeAR",
    "home_greeting": "जोहार MineSafeAR",
    **FORMAT_ONLY,
}

OLCK_HEADER = """\
<!--
  Santali (sat), Ol Chiki script — REVIEW TEMPLATE, NOT A TRANSLATION.

  Ol Chiki is the script Santali is officially written in (Unicode U+1C50-U+1C7F).
  This file is generated by tools/generate_translation_template.py.

  ## What is here

  Only the strings we are genuinely confident about are filled in. Everything
  else is a TODO comment holding the finished element: uncomment the line and
  replace the English text. Nothing here was machine-translated or guessed,
  because the module content is load-bearing - fire_module_extinguisher_correct
  names the extinguisher that is safe on a live electrical panel, and a plausible
  mistranslation of that is a safety defect rather than a typo.

  ## What a missing key does

  Nothing bad. Android falls back to values/strings.xml, so an untranslated
  screen renders in English. That is a supervisor-readable state, and it is why
  omitting a key is the correct way to say "not translated yet".

  ## Fonts

  Ol Chiki is absent from the bundled font set on a lot of Android builds, so
  these glyphs can render as empty boxes on the very device whose owner needs
  them. Two mitigations, in order of preference:

    1. Bundle Noto Sans Ol Chiki as a font resource and set it on the theme's
       typography. This is the real fix and is not done yet.
    2. Offer values-b+sat+Deva (transliterated Devanagari), which every Android
       device can render. The language picker lists both, each row labelled in
       Latin as well, so a worker can find the readable one even when the other
       row is boxes.

  ## Rules for whoever fills this in

  * Keep every %1$s / %1$d placeholder. They may be reordered - that is what the
    positional numbers are for - but one dropped or renumbered specifier is a
    runtime crash, not a layout bug.
  * The extinguisher colours are the answer the module teaches (IS 15683 / EN 3:
    black CO2, cream foam, red water). Translate the words, never the colours.
  * verify_result_valid / _invalid / _expired are read off a screen at arm's
    length during an inspection. Keep them short and mutually distinct.
-->"""

DEVA_HEADER = """\
<!--
  Santali (sat-Deva), transliterated Devanagari — REVIEW TEMPLATE, NOT A
  TRANSLATION.

  Generated by tools/generate_translation_template.py.

  ## Why this file exists alongside values-sat

  Ol Chiki is the correct script for Santali and values-sat is the primary
  target. This directory is the fallback for the practical problem that many
  Android devices ship no Ol Chiki font, so U+1C50-U+1C7F renders as empty
  boxes; Devanagari is universally bundled. A large share of Santali speakers in
  Jharkhand and Odisha are already schooled in Devanagari, so a transliteration
  is readable to them where boxes are not.

  This is a *transliteration of Santali*, not Hindi. The words are Santali; only
  the script is borrowed. Do not fill it in with Hindi - values-hi already
  exists, and a Hindi string served to someone who selected Santali is worse
  than English, because they will not know they are reading the wrong language.

  ## Everything else

  Same rules as values-sat/strings.xml: filled-in strings are only the ones we
  are confident of, every other key is a TODO comment holding the finished
  element, and an omitted key falls back to English. Keep the %1$s placeholders,
  keep the extinguisher colours, keep the three verdicts short.
-->"""

TODO_TAG = "TODO(santali)"


def load_source() -> list[str]:
    return SOURCE.read_text(encoding="utf-8").splitlines()


def render(confident: dict[str, str], header: str) -> str:
    out: list[str] = ['<?xml version="1.0" encoding="utf-8"?>', header, "<resources>"]
    in_source_comment = False
    translated = 0
    todo = 0

    for raw in load_source():
        line = raw.strip()

        # Copy the source's section comments through, so a reviewer sees the same
        # structure - including the translator notes on the fire and certificate
        # blocks, which are the two places a wrong translation does real damage.
        if in_source_comment:
            out.append(raw.rstrip())
            if "-->" in line:
                in_source_comment = False
            continue
        if line.startswith("<!--"):
            out.append(raw.rstrip())
            if "-->" not in line:
                in_source_comment = True
            continue

        if not line or line.startswith("<?xml") or line in ("<resources>", "</resources>"):
            if not line:
                out.append("")
            continue

        match = STRING_RE.match(line)
        if match is None:
            raise SystemExit(
                f"{SOURCE.name}: expected a single-line <string> element, got:\n  {line}\n"
                "This generator is deliberately text-based so escaping survives "
                "verbatim; reformat the source or teach it the new shape."
            )

        name = match.group("name")
        if 'translatable="false"' in match.group("attrs"):
            # Never appears in a translated file: the values are the same in every
            # locale by definition, and lint flags a copy.
            continue

        if name in confident:
            out.append(f'    <string name="{name}">{confident[name]}</string>')
            translated += 1
            continue

        # XML comments cannot contain "--" or end in "-". No current string does,
        # but fail loudly rather than emit a file that will not parse.
        if "--" in line:
            raise SystemExit(f'{name}: value contains "--", which cannot go in an XML comment')
        if line.endswith("-"):
            raise SystemExit(f"{name}: value ends in '-', which cannot end an XML comment")

        specifiers = FORMAT_RE.findall(line)
        if specifiers:
            out.append(f"    <!-- keeps: {' '.join(specifiers)} -->")
        out.append(f"    <!-- {TODO_TAG}: {line} -->")
        todo += 1

    out.append("</resources>")
    print(f"  {translated} translated, {todo} awaiting review", file=sys.stderr)
    return "\n".join(out) + "\n"


def main() -> None:
    if not SOURCE.is_file():
        raise SystemExit(f"missing {SOURCE}")

    targets = [
        (RES / "values-sat" / "strings.xml", CONFIDENT_OLCK, OLCK_HEADER),
        (RES / "values-b+sat+Deva" / "strings.xml", CONFIDENT_DEVA, DEVA_HEADER),
    ]
    for path, confident, header in targets:
        print(f"{path.relative_to(REPO)}:", file=sys.stderr)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(confident, header), encoding="utf-8")


if __name__ == "__main__":
    main()
