package com.minesafear.ar

import androidx.annotation.RawRes
import com.minesafear.R

/**
 * The 3D assets the AR layer can place on a detected plane.
 *
 * Ids point at files in `app/src/main/res/raw/` rather than `assets/`, because
 * [ARSessionManager.placeObjectAt] takes a `@RawRes Int`. That keeps model
 * references compile-checked instead of stringly-typed: rename or delete a file
 * and the build breaks, rather than a training module silently rendering nothing
 * on a worker's phone.
 *
 * ## Everything here is a placeholder
 *
 * All six models are generated by
 * `tools/generate_placeholder_models.py` from boxes and extruded polygons. They
 * are checked in so a fresh clone runs, and regenerable so nobody has to trust an
 * unattributed binary. They are also not art, and are not meant to ship.
 *
 * The one thing they do take seriously is **colour coding**, because identifying
 * an extinguisher by the colour of its body is the actual skill the fire module
 * tests. Replacing [EXTINGUISHER_CO2] with a model that is not black would break
 * the training, not just the looks.
 *
 * ## Swapping in the real assets
 *
 * **1. Fire extinguishers** — three today ([EXTINGUISHER_CO2],
 * [EXTINGUISHER_FOAM], [EXTINGUISHER_WATER]), and dry powder will be wanted for
 * the next module. Drop `extinguisher_co2.glb` and friends in `res/raw/`, point
 * the constants at them, and keep [EXTINGUISHER_SCALE_METRES] — a 9 kg
 * extinguisher really is about 0.55 m tall, and trainees should be judging reach
 * and weight from the model.
 *
 * **2. Exit sign** — [EXIT_SIGN] is floor-standing on a post, which is not where
 * signage lives. Real signage is wall-mounted, so the placement pass for it needs
 * [com.google.ar.core.Config.PlaneFindingMode.HORIZONTAL_AND_VERTICAL] and a
 * vertical-plane branch in [ARSessionManager]; the current pipeline is
 * horizontal-only by design (see `ArScene`). Until that lands, a post is an honest
 * stand-in rather than a sign floating in mid-air.
 *
 * **3. Exit arrows** — [EXIT_ARROW] is deliberately one model used for every
 * route, correct and decoy alike: a decoy that looks different from the right
 * answer is not a decoy. Note that an arrow's *heading* currently comes from the
 * anchor pose, whose yaw ARCore does not define meaningfully for a horizontal
 * plane hit, so arrows point in an arbitrary direction. Aiming them needs a
 * rotation on the node, which is a follow-up.
 *
 * **4. Gas cloud** — the leak-detection module. This one is *not* a `.glb`: a
 * static mesh reads as a grey blob. It wants a particle/volumetric effect, which
 * in Filament means either an animated glTF with an alpha-blended billboard
 * sheet, or a custom `filamat` material driven from
 * [io.github.sceneview.loaders.MaterialLoader]. Budget real time for it and keep
 * the interface here (`GAS_CLOUD`) so callers do not need to know the difference.
 *
 * **5. PPE icons** — helmet, gloves, goggles, harness, boots. These are UI-scale
 * markers pinned near equipment, not full models: prefer flat quads with a
 * texture atlas (one draw call for all five) over five separate meshes. If they
 * end up as `.glb`, group them in a nested `object Ppe`.
 *
 * ## Asset budget
 *
 * Keep each model under ~5 MB and ~50k triangles. These run on mid-range
 * hardware in a mine, and the whole app has to work offline, so every megabyte
 * here is a megabyte in the APK or in a sync payload.
 *
 * Sources for real assets that are safe to ship: the Khronos glTF Sample Assets
 * repository (CC0/CC-BY), NASA 3D Resources (public domain), and Smithsonian
 * Open Access (CC0). Record the licence of anything added here.
 */
object ArModels {

    /**
     * A 1x1x1 orange cube, origin at the centre of its base so it rests on a
     * plane instead of sinking half-way through it.
     *
     * Used only by `ARTestActivity`. Delete both together.
     */
    @RawRes
    val PLACEHOLDER_CUBE: Int = R.raw.placeholder_cube

    /** Black body: safe on live electrical equipment, leaves no residue. */
    @RawRes
    val EXTINGUISHER_CO2: Int = R.raw.placeholder_extinguisher_co2

    /** Cream body: flammable liquids. Water-based, so never on electrics. */
    @RawRes
    val EXTINGUISHER_FOAM: Int = R.raw.placeholder_extinguisher_foam

    /** Red body: ordinary combustibles only. Conducts, so never on electrics. */
    @RawRes
    val EXTINGUISHER_WATER: Int = R.raw.placeholder_extinguisher_water

    /** Realistic 3D fire extinguisher with pressure gauge, pull-pin, hose, nozzle & PASS instructions label. */
    @RawRes
    val EXTINGUISHER_REALISTIC: Int = R.raw.realistic_extinguisher

    /** Green panel on a post — see the note above about wall mounting. */
    @RawRes
    val EXIT_SIGN: Int = R.raw.placeholder_exit_sign

    /** Flat green chevron for floor route markings. One model for every route. */
    @RawRes
    val EXIT_ARROW: Int = R.raw.placeholder_exit_arrow

    /**
     * Longest edge, in metres, that a placed model is scaled to fit.
     *
     * 0.25 m is chosen so the placeholder cube is unmistakably visible at arm's
     * length without dominating the camera. Real assets should override this with
     * their true-world size — an extinguisher scaled to 0.25 m is a toy.
     */
    const val DEFAULT_SCALE_METRES: Float = 0.25f

    /** Height of a 9 kg extinguisher. Trainees judge reach and weight from this. */
    const val EXTINGUISHER_SCALE_METRES: Float = 0.55f

    /** Default height in metres above the floor for extinguishers to float above the surface. */
    const val EXTINGUISHER_DEFAULT_FLOAT_HEIGHT_METRES: Float = 0.25f

    /** Eye-height signage, so a trainee has to look up for it like the real thing. */
    const val EXIT_SIGN_SCALE_METRES: Float = 1.9f

    /** Long enough to read as a direction from standing height. */
    const val EXIT_ARROW_SCALE_METRES: Float = 0.9f
}
